name: speedify # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Speedify VPN (Community Created) # 79 char long summary
description: |
This Snap will only allow Speedify VPN access to the bare minimum of what it wants to run.

Speedify is a VPN service that allows you to bond multiple connections to the internet into 1 VPN connection to help you boost your internet speed.  Works on multiple platforms.

If you prefer to install it the "official" way, here is their link: https://support.speedify.com/article/562-how-to-install-speedify-on-linux

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
